version: 2

updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    groups:
      cargo-ark:
        patterns:
          - "ark-*"
      cargo:
        patterns:
          - "*"
        exclude-patterns:
          - "ark-*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      github-actions:
        patterns:
          - "*"
    exclude-paths:
      - .github/workflows/dagger.yaml
